# .github/workflows/publish.yml
name: publish

on:
  release:
    types: [published]

env:
  CORE_PROJECT_PATH: OneTimeLink.Core/OneTimeLink.Core.csproj
  EF_PROJECT_PATH: OneTimeLink.EntityFrameworkCore/OneTimeLink.EntityFrameworkCore.csproj

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          find . -name "*.csproj" -type f

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Pack
        run: |
          dotnet pack ${{ env.CORE_PROJECT_PATH }} --no-build --configuration Release --output nuget-packages
          dotnet pack ${{ env.EF_PROJECT_PATH }} --no-build --configuration Release --output nuget-packages

      - name: Publish to NuGet
        run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json